version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # HTTPS 트래픽을 위한 포트 추가
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - blue
      - green
    networks:
      - webnet

  blue:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - webnet

  green:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - webnet

networks:
  webnet:
