name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Check npm -v
      run: npm -v

    - name: create env file
      working-directory: ./
      run: |
        pwd
        touch .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        cat .env


    - name: zip file
      run: zip -r DC.zip ./src/* ./prisma/* ./scripts/* ./appspec.yml ./package.json ./package-lock.json ./.env ./deploy.sh ./docker-compose.yml ./Dockerfile ./nginx.conf

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./DC.zip s3://mydockerbucket3/deploy/


    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name mydocker-app
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name my-docker-group
        --s3-location bucket=mydockerbucket3,bundleType=zip,key=deploy/DC.zip